// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJPsewe929xiwX57Bhnq_A-E3my-IJmDA',
    appId: '1:261671791417:web:506297494e98dc5b6196e8',
    messagingSenderId: '261671791417',
    projectId: 'awesomeplace-40644',
    authDomain: 'awesomeplace-40644.firebaseapp.com',
    storageBucket: 'awesomeplace-40644.firebasestorage.app',
    measurementId: 'G-61SECGK3NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD52uGVCe76O0F172uO4zMzu5sgXQ4NQEk',
    appId: '1:261671791417:android:86c46f2b77d5432b6196e8',
    messagingSenderId: '261671791417',
    projectId: 'awesomeplace-40644',
    storageBucket: 'awesomeplace-40644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABRRLwO92jxpCkDxEfrBijePh4DIkWmYY',
    appId: '1:261671791417:ios:59ccc00f99fe3d4c6196e8',
    messagingSenderId: '261671791417',
    projectId: 'awesomeplace-40644',
    storageBucket: 'awesomeplace-40644.firebasestorage.app',
    iosBundleId: 'com.example.workoutPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABRRLwO92jxpCkDxEfrBijePh4DIkWmYY',
    appId: '1:261671791417:ios:59ccc00f99fe3d4c6196e8',
    messagingSenderId: '261671791417',
    projectId: 'awesomeplace-40644',
    storageBucket: 'awesomeplace-40644.firebasestorage.app',
    iosBundleId: 'com.example.workoutPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJPsewe929xiwX57Bhnq_A-E3my-IJmDA',
    appId: '1:261671791417:web:b3f38b5fc10b7b926196e8',
    messagingSenderId: '261671791417',
    projectId: 'awesomeplace-40644',
    authDomain: 'awesomeplace-40644.firebaseapp.com',
    storageBucket: 'awesomeplace-40644.firebasestorage.app',
    measurementId: 'G-TXTG4H210F',
  );
}
